// export const tabdleData = [
//     {
//       key: 1044,
//       employee: {
//         name: "John Brown"
//       },
//       age: 32,
//       address: "New York No. 1 Lake Park",
//       description:
//         "My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.",
//       decitions: [{comment: 'hot key', id: '2'}, {comment: 'link me', id: '1'}]
//     },
//     {
//       key: 1045,
//       employee: {
//         name: "Jim Green"
//       },
//       age: 42,
//       address: "London No. 1 Lake Park",
//       description:
//         "My name is Jim Green, I am 42 years old, living in London No. 1 Lake Park."
//     },
//     {
//         key: 1046,
//         employee: {
//           name: "Jim Green"
//         },
//         age: 41,
//         address: "London No. 1 Lake Park ff",
//         description:
//           "My name is Jim Green, I am 42 years old, "
//       }
//   ];

export const tableData = [
    {
        "roundTableRatingId": 9866,
        "ratingId": null,
        "employee": {
            "id": 6150,
            "positionId": 3064,
            "positionTitle": "Советник",
            "positionCode": "37451.03",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2150,
            "code": "0150",
            "email": "test150@test.ru",
            "personId": 1150,
            "firstName": "Амира",
            "lastName": "Барсукова",
            "middleName": "Алисеевна",
            "fullName": "Барсукова Амира Алисеевна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 47,
            "beginDate": "2008-01-10"
        },
        "decision": [
            {
                "id": 87,
                "comment": "213213",
                "decisionId": 2,
                "categoryName": "career"
            },
            {
                "id": 88,
                "comment": "dsadsadsa",
                "decisionId": 3,
                "categoryName": "individualPlan"
            },
            {
                "id": 89,
                "comment": "dddd",
                "decisionId": 3,
                "categoryName": "individualPlan"
            }
        ],
        "careerPlanId": 21011,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9867,
        "ratingId": null,
        "employee": {
            "id": 6151,
            "positionId": 3065,
            "positionTitle": "Советник",
            "positionCode": "37451.04",
            "orgUnitId": 4011,
            "orgUnitTitle": "Отдел разработки",
            "orgUnitCode": "0500.1-3",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2151,
            "code": "0151",
            "email": "test151@test.ru",
            "personId": 1151,
            "firstName": "Валерия",
            "lastName": "Глушкова",
            "middleName": "Платоновна",
            "fullName": "Глушкова Валерия Платоновна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6148,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 34,
            "beginDate": "2008-01-10"
        },
        "decision": [],
        "careerPlanId": 21012,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9865,
        "ratingId": 2,
        "employee": {
            "id": 6149,
            "positionId": 3063,
            "positionTitle": "Советник",
            "positionCode": "37451.02",
            "orgUnitId": 4009,
            "orgUnitTitle": "Бухгалтерия",
            "orgUnitCode": "0500.1-1",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2149,
            "code": "0149",
            "email": "test149@test.ru",
            "personId": 1149,
            "firstName": "Кира",
            "lastName": "Копылова",
            "middleName": "Мироновна",
            "fullName": "Копылова Кира Мироновна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6146,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 35,
            "beginDate": "2008-01-10"
        },
        "decision": [
            {
                "id": 90,
                "comment": "dsadsadas",
                "decisionId": 3,
                "categoryName": "individualPlan"
            }
        ],
        "careerPlanId": 21010,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9874,
        "ratingId": 4,
        "employee": {
            "id": 7097,
            "positionId": 3733,
            "positionTitle": "Специалист",
            "positionCode": "123654987",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 3096,
            "code": "0739",
            "email": "Test702@test.ru",
            "personId": 1703,
            "firstName": "Владлена",
            "lastName": "Кулибаба",
            "middleName": "Богдановна",
            "fullName": "Кулибаба Владлена Богдановна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 44,
            "beginDate": "2021-09-19"
        },
        "decision": [],
        "careerPlanId": 21290,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9871,
        "ratingId": null,
        "employee": {
            "id": 7094,
            "positionId": 3730,
            "positionTitle": "Специалист",
            "positionCode": "123654984",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 3093,
            "code": "0736",
            "email": "Test699@test.ru",
            "personId": 1700,
            "firstName": "Вениамин",
            "lastName": "Лобанов",
            "middleName": "Вадимович",
            "fullName": "Лобанов Вениамин Вадимович",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 37,
            "beginDate": "2021-09-19"
        },
        "decision": [],
        "careerPlanId": 21287,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9868,
        "ratingId": null,
        "employee": {
            "id": 6152,
            "positionId": 3066,
            "positionTitle": "Советник",
            "positionCode": "37451.05",
            "orgUnitId": 4009,
            "orgUnitTitle": "Бухгалтерия",
            "orgUnitCode": "0500.1-1",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2152,
            "code": "0152",
            "email": "test152@test.ru",
            "personId": 1152,
            "firstName": "Анна",
            "lastName": "Макарова",
            "middleName": "Артёмовна",
            "fullName": "Макарова Анна Артёмовна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6146,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 47,
            "beginDate": "2008-01-10"
        },
        "decision": [],
        "careerPlanId": 21013,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9872,
        "ratingId": null,
        "employee": {
            "id": 7095,
            "positionId": 3731,
            "positionTitle": "Специалист",
            "positionCode": "123654985",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 3094,
            "code": "0737",
            "email": "Test700@test.ru",
            "personId": 1701,
            "firstName": "Борислава",
            "lastName": "Медяник",
            "middleName": "Григорьевна",
            "fullName": "Медяник Борислава Григорьевна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 45,
            "beginDate": "2021-09-19"
        },
        "decision": [
            {
                "id": 91,
                "comment": "dsadsadsa",
                "decisionId": 2,
                "categoryName": "career"
            }
        ],
        "careerPlanId": 21288,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9873,
        "ratingId": null,
        "employee": {
            "id": 7096,
            "positionId": 3732,
            "positionTitle": "Специалист",
            "positionCode": "123654986",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 3095,
            "code": "0738",
            "email": "Test701@test.ru",
            "personId": 1702,
            "firstName": "Устин",
            "lastName": "Петрив",
            "middleName": "Евгеньевич",
            "fullName": "Петрив Устин Евгеньевич",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 35,
            "beginDate": "2021-09-19"
        },
        "decision": [],
        "careerPlanId": 21289,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9869,
        "ratingId": null,
        "employee": {
            "id": 6153,
            "positionId": 3067,
            "positionTitle": "Советник",
            "positionCode": "37451.06",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2153,
            "code": "0153",
            "email": "test153@test.ru",
            "personId": 1153,
            "firstName": "София",
            "lastName": "Соколова",
            "middleName": "Марковна",
            "fullName": "Соколова София Марковна",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 32,
            "beginDate": "2008-01-10"
        },
        "decision": [],
        "careerPlanId": 21014,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9875,
        "ratingId": null,
        "employee": {
            "id": 7182,
            "positionId": 3818,
            "positionTitle": "Руководитель отдела",
            "positionCode": "123655072",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 3181,
            "code": "0824",
            "email": "Test787@test.ru",
            "personId": 1788,
            "firstName": "Роман",
            "lastName": "Ткаченко",
            "middleName": "Фёдорович",
            "fullName": "Ткаченко Роман Фёдорович",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 39,
            "beginDate": "2021-09-19"
        },
        "decision": [],
        "careerPlanId": 21375,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    },
    {
        "roundTableRatingId": 9870,
        "ratingId": null,
        "employee": {
            "id": 6154,
            "positionId": 3068,
            "positionTitle": "Советник",
            "positionCode": "37451.07",
            "orgUnitId": 4010,
            "orgUnitTitle": "Департамент кадровой политики",
            "orgUnitCode": "0500.1-2",
            "orgUnitDivisionId": 4007,
            "orgUnitDivisionTitle": "АХД и сервисная инфраструктура",
            "orgUnitDivisionCode": "0500",
            "orgUnitCompanyId": 4008,
            "orgUnitCompanyTitle": "Госкорпорация «Росатом»",
            "orgUnitCompanyCode": "0500.1",
            "empCodeId": 2154,
            "code": "0154",
            "email": "test154@test.ru",
            "personId": 1154,
            "firstName": "Вадим",
            "lastName": "Туманов",
            "middleName": "Гордеевич",
            "fullName": "Туманов Вадим Гордеевич",
            "thumbUuid": null,
            "balanceUnitId": -10002,
            "balanceUnitTitle": "Госкорпорация «Росатом»",
            "balanceUnitCode": "trosAtom",
            "managerId": 6147,
            "employeeGroupId": 1,
            "statusId": 3,
            "age": 38,
            "beginDate": "2008-01-10"
        },
        "decision": [],
        "careerPlanId": 21015,
        "ued": {
            "uedCardId": null,
            "totalFactor": null,
            "statusTitle": null,
            "employeeIsManager": null,
            "finalGradeLastYearId": null,
            "averageRating": null,
            "managerRatingId": null,
            "managerComment": null,
            "managerRatingPtzn": null,
            "managerRatingValue": null,
            "managerRatingTeamProgress": null
        }
    }
].map(i => ({...i, key: i.roundTableRatingId}))
